/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Cashier } from './types';

export const INITIAL_CASHIERS: Cashier[] = [
  {
    id: 'valentina',
    name: 'Валентина',
    title: 'Стандартный канал #1',
    avatarColor: 'bg-red-600',
    baseSpeed: 1.2,
    currentSpeed: 1.2,
    stamina: 100,
    maxStamina: 100,
    fatigueRate: 0.0,
    friendliness: 3,
    errorRate: 0.0,
    errorCount: 0,
    isLocked: false,
    costToUnlock: 0,
    level: 1,
    xp: 0,
    xpNeeded: 100,
    specialtyKey: 'cancel_button',
    specialtyName: 'Стандартный сервис',
    specialtyDesc: 'Работает со стабильной скоростью без прерывов и ошибок.',
    traitDesc: 'Классический прибор обслуживания в системе массового обслуживания.',
    status: 'idle',
    errorCooldown: 0,
    totalServed: 0,
    totalItemsScanned: 0,
    tipsEarned: 0,
    restingSpeed: 10.0,
    assignedRegisterId: 0,
  },
  {
    id: 'artur',
    name: 'Артур',
    title: 'Стандартный канал #2',
    avatarColor: 'bg-indigo-505',
    baseSpeed: 1.2,
    currentSpeed: 1.2,
    stamina: 100,
    maxStamina: 100,
    fatigueRate: 0.0,
    friendliness: 3,
    errorRate: 0.0,
    errorCount: 0,
    isLocked: false,
    costToUnlock: 0,
    level: 1,
    xp: 0,
    xpNeeded: 100,
    specialtyKey: 'youth_vibe',
    specialtyName: 'Стандартный сервис',
    specialtyDesc: 'Работает со стабильной скоростью без прерывов и ошибок.',
    traitDesc: 'Классический прибор обслуживания в системе массового обслуживания.',
    status: 'idle',
    errorCooldown: 0,
    totalServed: 0,
    totalItemsScanned: 0,
    tipsEarned: 0,
    restingSpeed: 10.0,
    assignedRegisterId: 1,
  },
  {
    id: 'zinaida',
    name: 'Зинаида',
    title: 'Стандартный канал #3',
    avatarColor: 'bg-amber-500',
    baseSpeed: 1.2,
    currentSpeed: 1.2,
    stamina: 100,
    maxStamina: 100,
    fatigueRate: 0.0,
    friendliness: 3,
    errorRate: 0.0,
    errorCount: 0,
    isLocked: false,
    costToUnlock: 0,
    level: 1,
    xp: 0,
    xpNeeded: 100,
    specialtyKey: 'meteor_scan',
    specialtyName: 'Стандартный сервис',
    specialtyDesc: 'Работает со стабильной скоростью без прерывов и ошибок.',
    traitDesc: 'Классический прибор обслуживания в системе массового обслуживания.',
    status: 'idle',
    errorCooldown: 0,
    totalServed: 0,
    totalItemsScanned: 0,
    tipsEarned: 0,
    restingSpeed: 10.0,
    assignedRegisterId: 2,
  },
  {
    id: 'stepan',
    name: 'Степан',
    title: 'Стандартный канал #4',
    avatarColor: 'bg-emerald-600',
    baseSpeed: 1.2,
    currentSpeed: 1.2,
    stamina: 100,
    maxStamina: 100,
    fatigueRate: 0.0,
    friendliness: 3,
    errorRate: 0.0,
    errorCount: 0,
    isLocked: false,
    costToUnlock: 0,
    level: 1,
    xp: 0,
    xpNeeded: 100,
    specialtyKey: 'eternal_chat',
    specialtyName: 'Стандартный сервис',
    specialtyDesc: 'Работает со стабильной скоростью без прерывов и ошибок.',
    traitDesc: 'Классический прибор обслуживания в системе массового обслуживания.',
    status: 'idle',
    errorCooldown: 0,
    totalServed: 0,
    totalItemsScanned: 0,
    tipsEarned: 0,
    restingSpeed: 10.0,
    assignedRegisterId: 3,
  },
  {
    id: 'robot',
    name: 'Вектор',
    title: 'Стандартный канал #5',
    avatarColor: 'bg-slate-700',
    baseSpeed: 1.2,
    currentSpeed: 1.2,
    stamina: 100,
    maxStamina: 100,
    fatigueRate: 0.0,
    friendliness: 3,
    errorRate: 0.0,
    errorCount: 0,
    isLocked: false,
    costToUnlock: 0,
    level: 1,
    xp: 0,
    xpNeeded: 100,
    specialtyKey: 'no_fatigue',
    specialtyName: 'Стандартный сервис',
    specialtyDesc: 'Работает со стабильной скоростью без прерывов и ошибок.',
    traitDesc: 'Классический прибор обслуживания в системе массового обслуживания.',
    status: 'idle',
    errorCooldown: 0,
    totalServed: 0,
    totalItemsScanned: 0,
    tipsEarned: 0,
    restingSpeed: 10.0,
    assignedRegisterId: 4,
  },
];

export const HOURLY_TIMELINE: Record<string, number[]> = {
  'constant': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], // uniform distribution
  'rush-hours': [0.4, 0.5, 0.6, 0.7, 1.2, 1.5, 1.0, 0.8, 1.3, 2.2, 2.5, 1.8, 1.2, 0.7, 0.4], // 8:00 to 22:00 Peaks at lunch (13:00) and evening rush (17:00 - 18:00)
  'lunch-and-evening': [0.3, 0.4, 0.7, 1.8, 2.1, 1.2, 0.8, 0.7, 1.2, 2.4, 2.8, 1.9, 1.1, 0.6, 0.3], // High peaks around lunch and evening checkouts
  'silent-night': [0.1, 0.1, 0.2, 0.3, 0.5, 0.7, 0.8, 0.9, 1.2, 1.8, 2.9, 3.0, 2.0, 1.0, 0.4], // Slow morning, giant ramp up into evening
  'poisson-random': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], // Seed base
};

export const CUSTOMER_NAMES = [
  'Алексей', 'Мария', 'Дмитрий', 'Ольга', 'Александр', 'Ирина', 'Сергей', 'Татьяна',
  'Андрей', 'Елена', 'Михаил', 'Наталья', 'Артем', 'Анна', 'Николай', 'Екатерина',
  'Владимир', 'Светлана', 'Игорь', 'Юлия', 'Максим', 'Ксения', 'Роман', 'Маргарита',
  'Денис', 'Виктория', 'Антон', 'Дарья', 'Павел', 'Анастасия', 'Иван', 'Евгения',
  'Константин', 'Марина', 'Кирилл', 'Алла', 'Глеб', 'Валерия', 'Виктор', 'Вероника',
];
